name: train-delays
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python =3.10.*
# dependencies
  # maths/ datascience
  - numpy
  - pandas
  - scikit-learn
  # plotting
  - matplotlib
  # notebooks
  - jupyterlab >=3.0.13,<4  # for notebooks IDE
  - nbdime >=3  # for comparing notebooks
  - jupyterlab-git >=0.30  # for git in jupyterlab
# configuration/secrets
  - pyprojroot  # for project-oriented workflow
  - python-dotenv  # for environment variables
  - ruamel.yaml >=0.15  # for YAML files
# unit testing
  - pytest >=6  # for unit testing
  - pytest-cov  # for code coverage
  - pytest-mock  # for mocker fixture
  - pytest-xdist  # for parallel testing
  - pytest-profiling  # for code profiling
# code quality
  - pre-commit >=2.9.2 # for pre-commit git hooks
  - flake8 >=4.0.0  # for static analysis
  - flake8-bugbear  # for static analysis rules
  - flake8-comprehensions  # for static analysis rules
  - flake8-simplify  # for static analysis rules
  - pylint >=2.6.0  # for linting  # TODO: Check overlap with flake8
  - pydocstyle  # for docstring checking
  - mypy  # for static type checking
  - black  # for automatic code formatting
  - isort >=5.0.2  # for import standardization
  - rope  # for refactoring
# support
  - attrs >=21.3.0  # for data classes
# utilities
  - invoke  # for task execution
  - pandoc  # for conversion of markdown files
  - pip >=21.2  # for native python installer
  - pip:
    - torch
    - torch-geometric
    - types-PyYAML
    - schema
    - -e .  # project code
